-- PART 2: khachhang, nhanvien, sanpham

-- khachhang
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('66', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'nguyenvanbcheck123@gmail.com', '0987654321', 'Nguyễn Văn B', NULL, '456 Đường ABC, Quận 4, TP. HCM', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('1', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'a@gmail.com', '0912123456', 'Nguyễn Văn A', 'nguyenvana.png', 'Quận 3', '0', NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('2', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'b@gmail.com', '0922123456', 'Trần Thị B', NULL, 'Quận 1', '0', NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('3', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'c@gmail.com', '0912345678', 'nguyen van c', NULL, NULL, '0', '2025-12-16 00:00:00', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('4', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'd@gmail.com', '0913345678', 'nguyen van d', NULL, NULL, '0', '2025-12-16 00:00:00', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('6', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'e@gmail.com', '0398343124', 'd', NULL, NULL, '0', '2025-12-16 00:00:00', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('7', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', '1@gmail.com', '0387343124', 'a', NULL, NULL, '0', '2025-12-16 00:00:00', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('8', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'f@gmail.com', '0923456799', 'nguyen van f', NULL, NULL, '0', '2025-12-17 00:00:00', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('9', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'h@gmail.com', '0923456789', 'h', NULL, NULL, '0', '2025-12-17 00:00:00', NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('61', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', '1234@gmail.com', '0967645656', 'nguyen 1234', NULL, NULL, '0', NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('62', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'toan2121@gmail.com', '0987654329', 'toan2121', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('69', '$2a$10$NKXjcJDPsN2x4G2.bA7aKuQFltvIxsQNw3XRef8GlWSm4t3HYVGi2', 'eeeeemailcuaban@gmail.com', '0837643762', 'dev1222', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.khachhang (mataikhoan, matkhau, email, sdt, hoten, avatar, diachi, number_log, first_log, diemtichluy, id_restaurant, trangthai, firebase_uid) VALUES ('70', '$2a$10$lrOxKdq5.Zk.pVCgxzr8D.jSm4vr6mrVpGhBcO99S6CY5PunNlv/u', '0987467283@default.com', '0987467283', 'toannnnn', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL) ON CONFLICT DO NOTHING;

-- nhanvien
INSERT INTO public.nhanvien (manhanvien, id_restaurant, mavaitro, tennhanvien, email, password, mota, number_log, first_log, trangthai) VALUES ('9', '1', '1', 'Hoàng Văn I', 'hvi@gmail.com', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'Quản lý', '11', '2023-12-18', 't') ON CONFLICT DO NOTHING;
INSERT INTO public.nhanvien (manhanvien, id_restaurant, mavaitro, tennhanvien, email, password, mota, number_log, first_log, trangthai) VALUES ('1', '1', '1', 'Nguyễn Thị q', 'ntq@gmail.com', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'Thu ngân', '1', '2023-12-19', 't') ON CONFLICT DO NOTHING;
INSERT INTO public.nhanvien (manhanvien, id_restaurant, mavaitro, tennhanvien, email, password, mota, number_log, first_log, trangthai) VALUES ('2', '1', '2', 'Trần Văn Y', 'tvy@gmail.com', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'Phục vụ', '1', '2023-12-19', 't') ON CONFLICT DO NOTHING;
INSERT INTO public.nhanvien (manhanvien, id_restaurant, mavaitro, tennhanvien, email, password, mota, number_log, first_log, trangthai) VALUES ('4', '1', '2', 'Hoàng Văn F', 'hvf@gmail.com', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'Phục vụ', '11', '2023-12-18', 't') ON CONFLICT DO NOTHING;
INSERT INTO public.nhanvien (manhanvien, id_restaurant, mavaitro, tennhanvien, email, password, mota, number_log, first_log, trangthai) VALUES ('5', '1', '2', 'Hoàng Văn J', 'hvj@gmail.com', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'Phục Vụ', '11', '2023-12-18', 't') ON CONFLICT DO NOTHING;
INSERT INTO public.nhanvien (manhanvien, id_restaurant, mavaitro, tennhanvien, email, password, mota, number_log, first_log, trangthai) VALUES ('8', '1', '1', 'Trần Văn H', 'tvh@gmail.com', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'Phục vụ', '1', '2023-12-19', 't') ON CONFLICT DO NOTHING;
INSERT INTO public.nhanvien (manhanvien, id_restaurant, mavaitro, tennhanvien, email, password, mota, number_log, first_log, trangthai) VALUES ('10', '1', '3', 'nhan vien bep a', 'bep@gmail.com', '$2a$10$DQJDd90aXLBCwyNSEyT.XOJlilghS/WarFW197.FAw7inEAuqG5bC', 'Nhan vien bep', '1', '2023-12-19', 't') ON CONFLICT DO NOTHING;
INSERT INTO public.nhanvien (manhanvien, id_restaurant, mavaitro, tennhanvien, email, password, mota, number_log, first_log, trangthai) VALUES ('7', '1', '2', 'Nguyễn Thị G', 'ntg@gmail.com', '$2a$10$slCcZISm6OShXhhuaDZWOOo6egMGs5llXyTF2sjOy1uF8N2//nY5O', NULL, NULL, NULL, 't') ON CONFLICT DO NOTHING;
INSERT INTO public.nhanvien (manhanvien, id_restaurant, mavaitro, tennhanvien, email, password, mota, number_log, first_log, trangthai) VALUES ('3', '1', '2', 'Hoàng Văn E', 'hve@gmail.com', '$2a$10$OLc6pvUZJmtqnFnj1KOCNOyAxr441ziSIsvs9fxQM2pJRD9IwFgi2', NULL, NULL, NULL, 't') ON CONFLICT DO NOTHING;
INSERT INTO public.nhanvien (manhanvien, id_restaurant, mavaitro, tennhanvien, email, password, mota, number_log, first_log, trangthai) VALUES ('6', '1', '3', 'Hoàng Văn K', 'hvk@gmail.com', '$2a$10$e3BIh9a1HzcEBRBmBCMzaOj5K0TyVqe7ErRDq/osNv4c70oEczguK', NULL, NULL, NULL, 't') ON CONFLICT DO NOTHING;

-- sanpham
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('3', '2', 'Hamburger bò', 'Bánh hamburger', '45000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('5', '2', 'Gà rán', 'Gà rán giòn', '35000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('7', '1', 'Trà sữa Thái xanh', 'Trà sữa vị thái xanh thơm mát', '32000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('8', '1', 'Hồng trà sữa', 'Trà sữa truyền thống đậm vị trà', '28000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('9', '2', 'Pizza Hải sản', 'Pizza nhân tôm, mực, thanh cua', '125000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('10', '3', 'Mì Ý Sốt Bò Bằm', 'Mì Ý sốt cà chua và thịt bò bằm', '55000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('11', '1', 'Nước ép Cam', 'Cam tươi nguyên chất 100%', '35000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('12', '3', 'Gà sốt Cay Hàn Quốc', 'Gà chiên giòn sốt cay ngọt', '45000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('13', '1', 'Sinh tố Bơ', 'Bơ sáp xay cùng sữa đặc', '40000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('14', '2', 'Khoai tây múi cau', 'Khoai tây cắt múi cau chiên giòn', '25000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('15', '1', 'Trà đào cam sả', 'Trà đào kết hợp cam và sả tươi', '38000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('16', '3', 'Salad Ức Gà', 'Salad rau củ kèm ức gà áp chảo', '48000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('17', '4', 'Chè khúc bạch', 'Chè khúc bạch trân châu đường đen', '25000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('18', '4', 'Bánh Flan', 'Bánh Flan cốt dừa thơm béo', '15000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('20', '4', 'Sữa chua dẻo', 'Sữa chua dẻo xắt miếng kèm bột ca cao', '30000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('21', '4', 'Kem bơ Đà Lạt', 'Bơ sáp xay nhuyễn kèm kem vani viên', '45000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('22', '3', 'Phở bò Nam Định', 'Phở bò đặc sản nổi tiếng Nam Định', '50000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('23', '3', 'Phở bò Lý Thái Tổ', 'Phở bò tái chín', '65000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('1', '1', 'Trà sữa trân châu đường đen', 'Thức uống ngọt, trân châu đường đen', '25000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('24', '1', 'Ca-fe đen', 'ca-fe đen đá ít đường', '25000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('4', '2', 'Khoai tây chiên', 'Khoai tây chiên giòn', '20000') ON CONFLICT DO NOTHING;
INSERT INTO public.sanpham (masanpham, madanhmuc, tensanpham, mota, gia) VALUES ('25', '3', 'Cơm rang dưa bò', 'Cơm rang dưa bò ngon nhức nách', '35000') ON CONFLICT DO NOTHING;

SELECT setval('public.khachhang_mataikhoan_seq', COALESCE((SELECT MAX(mataikhoan) FROM public.khachhang),1));
SELECT setval('public.nhanvien_manhanvien_seq', COALESCE((SELECT MAX(manhanvien) FROM public.nhanvien),1));
SELECT setval('public.sanpham_masanpham_seq', COALESCE((SELECT MAX(masanpham) FROM public.sanpham),1));