# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/DucToanRestaurant
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server
server.address=0.0.0.0
server.port=8080

# JWT Secret Key - This key is 256 bits (32 bytes) long and Base64 encoded for safety.
jwt.secret=c2VjcmV0a2V5Zm9yand0c2VjdXJpdHlzcHJpbmdib290YXBwbGljYXRpb24=


nhanVien.api.key = nguyenductoan123456


# Gemini API Configuration

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent